######################################################################
# Automatically generated by qmake (3.0) Fri Mar 20 00:29:45 2015
######################################################################

QT += serialport

TEMPLATE = app
TARGET = propman
INCLUDEPATH += .

CONFIG += debug console
CONFIG -= debug_and_release

# Input
SOURCES += \
    main.cpp \
    Loader.cpp \

HEADERS += \
    Loader.h
