#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(pmanager)

Q_DECLARE_LOGGING_CATEGORY(ploader)

Q_DECLARE_LOGGING_CATEGORY(pdevice)
Q_DECLARE_LOGGING_CATEGORY(pserial)
Q_DECLARE_LOGGING_CATEGORY(pxbee)
Q_DECLARE_LOGGING_CATEGORY(pgpio)

Q_DECLARE_LOGGING_CATEGORY(psession)
Q_DECLARE_LOGGING_CATEGORY(pimage)
